"""One inspirational line per day of the year, indexed by day-of-year in the daily brief."""

QUOTES = [
    "Small steps still move you forward.",
    "Make today count.",
    "Progress beats perfection.",
    "Do one hard thing first.",
    "Consistency beats intensity.",
    "You have time for what matters.",
    "Ship something today.",
    "Calm mind, steady hands.",
    "Finish what you start.",
    "One day at a time.",
    "Momentum is built, not found.",
    "Start now, refine later.",
    "A little every day adds up fast.",
    "Begin before you feel ready.",
    "The work rewards the patient.",
    "Show up even when it is hard.",
    "Slow progress is still progress.",
    "Doubt kills more dreams than failure.",
    "Action cures fear.",
    "Your future is built today.",
    "Trust the process you set.",
    "Effort compounds quietly.",
    "Be stubborn about goals, flexible about methods.",
    "Discipline is freedom.",
    "Done is better than perfect.",
    "The first step is the whole trick.",
    "Keep the promise you made yourself.",
    "Quiet effort, loud results.",
    "You are closer than you think.",
    "Small wins stack into big ones.",
    "Focus turns effort into results.",
    "Simplify until it is obvious.",
    "Less noise, more signal.",
    "One thing at a time, done well.",
    "Attention is your rarest resource.",
    "Protect your mornings.",
    "Say no to guard your yes.",
    "Depth beats breadth.",
    "Clear goals make easy decisions.",
    "Cut the trivial, keep the vital.",
    "Rushing is slow in disguise.",
    "Master the boring fundamentals.",
    "Repetition builds mastery.",
    "Sharpen the axe before you cut.",
    "Plan the work, then work the plan.",
    "A calm start beats a frantic sprint.",
    "Finish the small things too.",
    "Order your day and it orders you.",
    "Do the next right thing.",
    "Win the morning, win the day.",
    "Courage is fear that kept going.",
    "Feel the fear and do it anyway.",
    "The brave stumble forward.",
    "Comfort is a slow trap.",
    "Growth lives outside the easy.",
    "Risk a little to gain a lot.",
    "Speak up, then figure it out.",
    "Boldness has quiet rewards.",
    "Fear shrinks when you face it.",
    "Leap and build your wings down.",
    "The hard road is the shortcut.",
    "Dare to be a beginner.",
    "Your comfort zone is a cage.",
    "Nerves mean you care.",
    "Do it scared.",
    "Fortune favors the willing.",
    "Ask for what you want.",
    "One brave choice changes a day.",
    "Bet on yourself.",
    "Face it, then it is smaller.",
    "Every expert was once lost.",
    "Learn something small today.",
    "Mistakes are tuition, pay attention.",
    "Curiosity outlasts talent.",
    "Ask the dumb question.",
    "Read a little, think a lot.",
    "Feedback is a gift, unwrap it.",
    "Stay a student of your craft.",
    "Knowledge stacks like bricks.",
    "The more you learn, the more you see.",
    "Practice beats theory.",
    "Fail fast, learn faster.",
    "Understand it, then simplify it.",
    "Teach it to truly learn it.",
    "A good question opens doors.",
    "Grow through what you go through.",
    "Skill is patience made visible.",
    "Notice what you keep avoiding.",
    "Wisdom is scar tissue with sense.",
    "Be curious, not judgmental.",
    "Learn the rules, then bend them.",
    "Read the manual eventually.",
    "Every day teaches if you listen.",
    "Turn setbacks into data.",
    "Fall seven times, rise eight.",
    "Storms make deeper roots.",
    "You survived every bad day so far.",
    "Bend, do not break.",
    "Rest is part of the work.",
    "Healing is not a straight line.",
    "Endure now, thank yourself later.",
    "Pressure can polish or crush, choose.",
    "The wound is where light enters.",
    "Keep going, the tunnel ends.",
    "Setbacks are setups in disguise.",
    "Grit outlasts talent.",
    "This too will pass.",
    "Strength grows in the struggle.",
    "Fall down, get up, repeat.",
    "You are more durable than you feel.",
    "Slow breath, steady heart.",
    "The comeback beats the setback.",
    "Persist quietly.",
    "Hard days build strong people.",
    "Hold on, then hold better.",
    "Every storm runs out of rain.",
    "Kindness is never wasted.",
    "Say thank you and mean it.",
    "Gratitude turns enough into plenty.",
    "Be the calm in someone's storm.",
    "Small kindness, large ripple.",
    "Notice the good, name it.",
    "Lift someone as you climb.",
    "Give without keeping score.",
    "A warm word costs nothing.",
    "Count your blessings, not your lacks.",
    "Listen more than you speak.",
    "Compassion is strength, not softness.",
    "Share the credit freely.",
    "Kind people are quietly powerful.",
    "Gratitude is a superpower.",
    "Make someone's day lighter.",
    "Assume good intent.",
    "Generosity returns in strange ways.",
    "Be gentle, everyone is fighting something.",
    "Thank the people who help you.",
    "The best time to start was earlier, the next best is now.",
    "Motion beats meditation on it.",
    "Start ugly, improve later.",
    "A draft beats a blank page.",
    "Take the first small action.",
    "Stop planning, start doing.",
    "Begin, and the way appears.",
    "Ideas are cheap, execution is rare.",
    "Just open the file.",
    "Do it now, perfect it never.",
    "The best plan is one you begin.",
    "Move first, motivation follows.",
    "One push starts the flywheel.",
    "Act, then adjust.",
    "Waiting is the slowest strategy.",
    "Today is a fine day to begin.",
    "Start where you stand.",
    "Something beats nothing.",
    "Launch before you are ready.",
    "Break it small, then start.",
    "Patience is quiet confidence.",
    "Good things take the time they take.",
    "Plant now, harvest later.",
    "Hurry less, arrive sooner.",
    "Time rewards those who show up.",
    "Let it simmer.",
    "Trust the slow build.",
    "Seeds do not sprout overnight.",
    "The long game always wins.",
    "Give it a season, not a day.",
    "Steady wins the distance.",
    "Ripening cannot be rushed.",
    "Delay is not denial.",
    "Compounding needs time to work.",
    "Water it and wait.",
    "The wait is part of the reward.",
    "Great things grow slowly.",
    "Be patient with your progress.",
    "Time magnifies small habits.",
    "Roots first, fruit later.",
    "Slow is smooth, smooth is fast.",
    "Your mindset sets your ceiling.",
    "Choose your attitude first.",
    "Thoughts become the day.",
    "Guard your inner voice.",
    "You become what you repeat.",
    "See problems as puzzles.",
    "Reframe the day, change the day.",
    "What you focus on grows.",
    "Optimism is a discipline.",
    "Feed the wolf you want to win.",
    "Believe it is possible, then act.",
    "Your story is still being written.",
    "Turn have to into get to.",
    "Perspective is a choice.",
    "Mind the story you tell yourself.",
    "A good mood is worth protecting.",
    "Assume it can be done.",
    "Change your view, change your day.",
    "Hope is a strategy when paired with work.",
    "Expect good, prepare well.",
    "Attitude is the paintbrush of the mind.",
    "Purpose makes hard work light.",
    "Know your why and the how follows.",
    "Do work that matters to you.",
    "Serve something bigger than yourself.",
    "Meaning beats motivation.",
    "Leave it better than you found it.",
    "Chase progress, not applause.",
    "A clear why survives any how.",
    "Build things you would be proud of.",
    "Purpose is fuel that never runs dry.",
    "Aim at what you respect.",
    "Do it for the person you are becoming.",
    "Small work, done with care, matters.",
    "Let your values pick your path.",
    "Work like it counts, it does.",
    "Find the meaning, keep the fire.",
    "Be useful, that is enough.",
    "Make your effort mean something.",
    "Align your days with your values.",
    "Legacy is built in ordinary days.",
    "Do good quietly.",
    "You are capable of more than today asks.",
    "Believe you can, then begin.",
    "Back yourself before others do.",
    "You have done hard things before.",
    "Your potential is not spent.",
    "Speak to yourself like a friend.",
    "You are allowed to take up space.",
    "Confidence is built, not given.",
    "Trust the version of you that tried.",
    "You are enough, and you can grow.",
    "Own your yes and your no.",
    "Stand tall in who you are.",
    "You are the author here.",
    "Give yourself some credit.",
    "Your pace is still forward.",
    "Be proud of quiet progress.",
    "You can handle the next step.",
    "Doubt is not a verdict.",
    "Root for yourself out loud.",
    "You are becoming, not behind.",
    "Rest so you can rise.",
    "Sleep is a performance tool.",
    "Recovery is where growth lands.",
    "Protect your energy.",
    "You cannot pour from empty.",
    "Slow down to speed up.",
    "A tired mind lies, rest it.",
    "Pause without guilt.",
    "Breaks are part of the plan.",
    "Recharge, then charge.",
    "Guard your peace like it matters.",
    "Stillness sharpens the next move.",
    "Take the walk.",
    "Silence is productive too.",
    "Let the day breathe.",
    "Rest is not quitting.",
    "Refill before you run dry.",
    "Quiet the noise, hear yourself.",
    "Step back to see the whole board.",
    "Peace is a kind of progress.",
    "Choose people who lift you.",
    "You rise with your circle.",
    "Be someone others can count on.",
    "Community carries what solo cannot.",
    "Ask for help, it is strength.",
    "Reach out before you burn out.",
    "Good company is good medicine.",
    "Give people your full attention.",
    "Surround yourself with builders.",
    "A team beats a hero.",
    "Show up for your people.",
    "Encourage more than you critique.",
    "Two heads light a dark room.",
    "Belong somewhere on purpose.",
    "Keep the friends who tell you truth.",
    "Lend a hand today.",
    "Loyalty is built in small moments.",
    "Celebrate others loudly.",
    "You are not meant to do it alone.",
    "Strong roots make strong branches.",
    "Aim higher than comfortable.",
    "Set the bar, then clear it.",
    "Dream big, start small.",
    "Great goals need daily deposits.",
    "Write the goal where you see it.",
    "Stretch goals grow you.",
    "Decide the destination, enjoy the road.",
    "A goal without a step is a wish.",
    "Turn the dream into a schedule.",
    "Reach for it, then reach again.",
    "Big vision, small next step.",
    "What would future you thank you for?",
    "Chase a summit worth the climb.",
    "Define the win before you start.",
    "Ambition plus patience wins.",
    "Set goals that scare and thrill you.",
    "Measure what matters, ignore the rest.",
    "Aim, then adjust, then aim again.",
    "Make the target clear.",
    "Progress needs a direction.",
    "Keep it simple and keep going.",
    "Trust your training.",
    "Let good enough be finished.",
    "Choose progress over comfort today.",
    "The obstacle is the way.",
    "Turn pressure into practice.",
    "Be the calm professional.",
    "Answer effort with more effort.",
    "Outlast the hard part.",
    "Make peace with slow days.",
    "Keep your standards, drop the panic.",
    "Do the reps nobody sees.",
    "Excellence is a habit, not a mood.",
    "Show up, that is half the battle.",
    "Win the next five minutes.",
    "Control the controllables.",
    "Let results follow the work.",
    "Small disciplines, large freedom.",
    "Be relentless about the basics.",
    "Stay in your own lane, at your own pace.",
    "The grind is quiet, the payoff is loud.",
    "Effort today, ease tomorrow.",
    "Keep your word to yourself.",
    "Choose action over anxiety.",
    "Do less, but better.",
    "Make room for what matters.",
    "Guard the main thing.",
    "Trim the day to its core.",
    "One priority beats ten intentions.",
    "Clarity is a competitive edge.",
    "Say it plainly, do it simply.",
    "The essential hides in the quiet.",
    "Subtract until it shines.",
    "A focused hour beats a scattered day.",
    "Protect deep work fiercely.",
    "End the day a step ahead.",
    "Tidy space, clear head.",
    "Finish strong, then rest well.",
    "Tomorrow starts with tonight.",
    "Leave a little in the tank for people.",
    "Be hard on the problem, soft on people.",
    "Let today be a good link in the chain.",
    "Keep planting, keep watering, keep going.",
    "Aim for better, not flawless.",
    "The quiet hours build the loud wins.",
    "Trade excuses for reasons.",
    "Be the reason someone keeps going.",
    "Steady hands finish the job.",
    "Choose the harder right over the easy wrong.",
    "Your habits are voting for your future.",
    "Make the bed, win the first battle.",
    "Chase clarity, not certainty.",
    "Do the thing you have been avoiding.",
    "Progress hides in unglamorous work.",
    "Keep your head up and your standards higher.",
    "Turn a bad start into a good finish.",
    "Effort is the one thing fully yours.",
    "Build the habit, not just the mood.",
    "Small honesty beats big pretending.",
    "Do right when no one is watching.",
    "Let discipline carry you past feelings.",
    "One good decision seeds the next.",
    "Show the world your quiet grit.",
    "Earn the evening with the morning.",
    "Keep it kind, keep it moving.",
    "Be the steady one today.",
    "Leave nothing important for someday.",
]
